---

# Returns:
# * _aws_subnet_id
# * _aws_subnet_name
- include_tasks: gather_facts.yml

- name: fail if no subnet was found
  assert:
    that:
      - _aws_subnet_facts.subnets is defined
      - _aws_subnet_facts.subnets | length == 1
    msg: Not exactly one Subnet has been found

- name: fail if no eip was found
  assert:
    that:
      - _aws_eip_facts.addresses is defined
      - _aws_eip_facts.addresses | length == 1
    msg: Not exactly one eip has been found

- name: set eip id and name
  set_fact:
    _aws_eip_id: "{{ _aws_eip_facts.addresses[0].allocation_id }}"
    _aws_eip_ip: "{{ _aws_eip_facts.addresses[0].public_ip }}"

# Idempotence Issue
# -----------------
#
# ec2_vpc_nat_gateway returns a hard-coded ID in chek mode (nat-123456789)
# this results in showing the playbook as 'changed' when doing a dry run.
# To overcome this issue we do the following:
#
# 1. Gather existing NAT GW in that subnet
# 2. If found:
#    2.1. Use its ID for tagging
# 3. If not found:
#    3.1. Create it
#    3.2. Gather facts again to find its id
#    3.3  Use its ID for tagging

###
### create nat gateway if not exists
###

- name: "create nat gateway for Subnet with ID {{ _aws_subnet_id }}"
  ec2_vpc_nat_gateway:
    # Fixed values
    state: present
    if_exist_do_not_create: True
    wait: True
    wait_timeout: 300
    # Looked-up values
    subnet_id: "{{ _aws_subnet_id }}"
    # Optional values
    allocation_id: "{{ _aws_eip_id | default(omit) }}"
    region: "{{ natgw.region | default(aws_vpc_nat_default_region | default(omit)) }}"
    aws_access_key: "{{ lookup('ENV', 'AWS_ACCESS_KEY') | default(omit) }}"
    aws_secret_key: "{{ lookup('ENV', 'AWS_SECRET_KEY') | default(omit) }}"
    security_token: "{{ lookup('ENV', 'AWS_SECURITY_TOKEN') | default(omit) }}"
    profile: "{{ aws_vpc_nat_profile | default(omit) }}"
  when:
    - _aws_vpc_nat_facts.result | length == 0

- name: register created nat gateway
  ec2_vpc_nat_gateway_facts:
    aws_access_key: "{{ lookup('ENV', 'AWS_ACCESS_KEY') | default(omit) }}"
    aws_secret_key: "{{ lookup('ENV', 'AWS_SECRET_KEY') | default(omit) }}"
    security_token: "{{ lookup('ENV', 'AWS_SECURITY_TOKEN') | default(omit) }}"
    profile: "{{ aws_vpc_nat_profile | default(omit) }}"
    region: "{{ natgw.region | default(aws_vpc_nat_default_region | default(omit)) }}"
    filters: "{{ _aws_vpc_nat_gw_filter | get_attr('key', 'val') }}"
  register: _aws_vpc_nat_facts


###
### Tag nat gateway
###

- name: set natgw tags
  set_fact:
    _aws_vpc_natgw_tags: |
      {{
        natgw.tags | default([]) + [{
          'key': 'Name',
          'val': natgw.name
        }]
      }}

- name: "ensure nat gateway with ID {{ _aws_vpc_nat_facts.result[0].nat_gateway_id }} is tagged"
  ec2_tag:
    # Fixed values
    state: present
    # Looked-up values
    resource: "{{ _aws_vpc_nat_facts.result[0].nat_gateway_id }}"
    # Required values
    tags: "{{ _aws_vpc_natgw_tags | get_attr('key', 'val') }}"
    # Optional values
    region: "{{ natgw.region | default(aws_vpc_nat_default_region | default(omit)) }}"
    aws_access_key: "{{ lookup('ENV', 'AWS_ACCESS_KEY') | default(omit) }}"
    aws_secret_key: "{{ lookup('ENV', 'AWS_SECRET_KEY') | default(omit) }}"
    security_token: "{{ lookup('ENV', 'AWS_SECURITY_TOKEN') | default(omit) }}"
    profile: "{{ aws_vpc_nat_profile | default(omit) }}"
  when:
    - _aws_vpc_nat_facts.result is defined
    - _aws_vpc_nat_facts.result | length == 1
    - _aws_vpc_nat_facts.result.0 is defined
    - _aws_vpc_nat_facts.result[0].nat_gateway_id is defined
