---

- name: combine eip filter
  set_fact:
    _aws_vpc_nat_eip_filter: |
      {{
        aws_vpc_nat_eip_filter_additional + natgw.eip_filter
      }}

- name: gather eip facts by filter
  ec2_eip_facts:
    aws_access_key: "{{ lookup('ENV', 'AWS_ACCESS_KEY') | default(omit) }}"
    aws_secret_key: "{{ lookup('ENV', 'AWS_SECRET_KEY') | default(omit) }}"
    security_token: "{{ lookup('ENV', 'AWS_SECURITY_TOKEN') | default(omit) }}"
    profile: "{{ aws_vpc_nat_profile | default(omit) }}"
    region: "{{ natgw.region | default(aws_vpc_nat_default_region) }}"
    filters: "{{ _aws_vpc_nat_eip_filter | get_attr('key', 'val') }}"
  register: _aws_eip_facts
