---

###
### Main entrypoint
###
- include_tasks: create_nat_gateway.yml
  loop_control:
    loop_var: natgw
  with_items:
    - "{{ aws_vpc_nat_gateway }}"
  when: aws_vpc_nat_state == "present"

- include_tasks: delete_nat_gateway.yml
  loop_control:
    loop_var: natgw
  with_items:
    - "{{ aws_vpc_nat_gateway }}"
  when: aws_vpc_nat_state == "absent"
